### ISSUE TITLE
mss_config_clk_rst doesn't support enabling the FPGA fabric

### ISSUE THREAD

**Issue by hughbreslin** [polarfire-soc/platform#10]
The mss_config_clk_rst function doesn't support setting the SOFT_RESET_CR_FPGA bit. This bit is used to drive the reset output of the MSS to the FPGA fabric and without setting it none of the FIC peripherals are useable when the MSS to FPGA reset is used even if the FIC is out of reset. 

Please add support for the FPGA reset to this function as the FICs are automatically taken out of reset [here](https://github.com/polarfire-soc/platform/blob/main/mpfs_hal/startup_gcc/system_startup.c#L179) but not usable.

**Comment by bkzshabbaz** [comment]
Would this issue be related to a problem I reported about interacting with Fabric IP over FIC3?

https://github.com/polarfire-soc/polarfire-soc-bare-metal-examples/issues/8

**Comment by nitindeshpande** [comment]
@bkzshabbaz, yes the issue is related.
@hughbreslin, The support will be available in the upcoming revision.

**Comment by hughbreslin** [comment]
This issue is resolved with the [v2022.08 platform](https://github.com/polarfire-soc/platform/releases/tag/2022.08) release.
