### ISSUE TITLE
MSS_SPI_init doesn't permit use of B Context 

### ISSUE THREAD

**Issue by DrEamonnG** [polarfire-soc/platform#15]
All of the MSS_SPI_.... functions in 'mss_spi.c' contain this ASSERT

    ASSERT((this_spi == &g_mss_spi0_lo) || (this_spi == &g_mss_spi0_hi) 
            || (this_spi == &g_mss_spi1_lo) || (this_spi == &g_mss_spi1_hi));   

except for MSS_SPI_init that contains 
    ASSERT((this_spi == &g_mss_spi0_lo) || (this_spi == &g_mss_spi1_lo));
instead.

It therefore fails for the '.._hi' options.

**Comment by hughbreslin** [comment]
Hi @DrEamonnG thanks for pointing this out, we have a fix internally and it should be available in the next couple of weeks.

**Comment by nitindeshpande** [comment]
Fixed with 2022.12.
